ToonYou:
  motion_module:
    # - "models/Motion_Module/mm_sd_v14.ckpt"
    - "models/Motion_Module/animatediff/mm_sd_v15_v2.ckpt"

  dreambooth_path: "models/DreamBooth_LoRA/toonyou_beta3.safetensors"
  lora_model_path: ""

  seed:           [42]
  steps:          25
  guidance_scale: 7.5

  prompt:
    - "best quality, masterpiece, 1girl, looking at viewer, blurry background, upper body, contemporary, dress"

  n_prompt:
    - ""
