image_finetune: false

output_dir: "outputs"
pretrained_model_path: "models/StableDiffusion/stable-diffusion-v1-5"
pretrained_motion_module_path: "models/Motion_Module/animatediff/mm_sd_v15_v2.ckpt"
unet_checkpoint_path: ""
dreambooth_model_path: "models/DreamBooth_LoRA/toonyou_beta3.safetensors"

unet_additional_kwargs:
  use_motion_module              : true
  motion_module_resolutions      : [ 1,2,4,8 ]
  unet_use_cross_frame_attention : false
  unet_use_temporal_attention    : false
  use_inflated_groupnorm: true # false for mm v1, true for mm v2

  motion_module_type: Vanilla
  motion_module_mid_block: true # false for v1, true for v2
  motion_module_kwargs:
    num_attention_heads                : 8
    num_transformer_block              : 1
    attention_block_types              : [ "Temporal_Self", "Temporal_Self" ]
    temporal_position_encoding         : true
    temporal_position_encoding_max_len : 32 # 24 for v1, 32 for v2
    temporal_attention_dim_div         : 1
    zero_initialize                    : true

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

train_data:
  csv_path:        "train_data/video_caption.csv"
  video_folder:    "train_data"
  sample_size:     256
  sample_stride:   1 # only for gif dataset!!
  sample_n_frames: 12 # debug. without more memory reduce methods, 12 for 3090 

validation_data:
  prompts:
    - "best quality, masterpiece, 1girl, looking at viewer, blurry background, upper body, contemporary, dress"
  num_inference_steps: 25
  guidance_scale: 7.5

trainable_modules:
  - "motion_modules."

learning_rate:    5.e-5
train_batch_size: 1 # debug
gradient_accumulation_steps: 4 # debug

max_train_epoch:      -1
max_train_steps:      10000
checkpointing_epochs: -1
checkpointing_steps:  200

validation_steps:       250
validation_steps_tuple: [1, 50, 100]

global_seed: 10788741199826055526
mixed_precision_training: true
enable_xformers_memory_efficient_attention: True

gradient_checkpointing: false # needed for 3090 to fix OOM. but somehow it makes graident update fail currently

is_debug: False
